apiVersion: v1
kind: Service
metadata:
  name: customers-service
spec:
  selector:
    app: customers
  type: LoadBalancer
  ports:
    - name: http
      nodePort: 30020
      port: 3002
      protocol: TCP
      targetPort: 3002
    - name: https
      nodePort: 30021
      port: 443
      protocol: TCP
      targetPort: 3002