apiVersion: v1
kind: Service
metadata:
  name: orders-service
spec:
  selector:
    app: orders
  type: LoadBalancer
  ports:
    - name: http
      nodePort: 30010
      port: 3001
      protocol: TCP
      targetPort: 3001
    - name: https
      nodePort: 30011
      port: 443
      protocol: TCP
      targetPort: 3001